---
- hosts: unifi
  tasks:
    - name: ubnt apt source
      copy:
        src: files/100-ubnt.list
        dest: /etc/apt/sources.list.d/100-ubnt.list

    - name: ubnt apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 06E85760C0A52C50

    - name: apt update
      apt:
        update_cache: yes

    - name: apt packages
      apt: name={{item}} state=latest
      with_items:
        - unifi
        - haveged # prevents /dev/random blocking
